#!/bin/bash

RM='rm'
base="*.aux *.log *.blg *.lof *.lot *.synctex.gz*"
bbl="*.bbl"
toc="*.toc"


for a in $@; do
        if [ "$a" = "-b" ]; then
                bbl="*.bbl"
        fi
        if [ "$a" = "-t" ]; then
                toc="*.toc"
        fi
        if [ "$a" = "-a" ]; then
                bbl="*.bbl"
                toc="*.toc"
        fi
done

echo "cleaning $base $bbl $toc from $PWD"
$RM $base $bbl $toc
